### ISSUE TITLE
Images and math in tab headings broken in 2.0.0

### ISSUE THREAD

**Issue by jmd-dk** [executablebooks/sphinx-tabs#101]
**Describe the bug**

Placing images and math in tab headings/titles does not work in version 2.0.0.

**To Reproduce / Expected behavior**

I'm not sure if it is (was) a deliberate feature, but prior to 2.0.0 one could have tabs like what is shown [here](https://jmd-dk.github.io/concept/installation.html#supported-platforms). The Sphinx code generating this is of the form
```rst
.. tabs::

   .. tab:: |linux| :math:`\,\,` Linux

      Tab 1 text...

   .. tab:: |windows| :math:`\,\,` Windows

      Tab 2 text
```
where `|linux|` and `|windows|` are images defined as
```rst
.. |linux| image:: /_static/linux.png
   :height: 35px

.. |windows| image:: /_static/windows.png
   :height: 35px
```
I use `:math:` simply to produce some whitespace between the images and the titles.

With sphinx-tabs 2.0.0 we get the following:
![tabs](https://user-images.githubusercontent.com/9202794/106959369-dbe64f00-673a-11eb-929d-0c76b0d9e474.png)
Neither the image nor the math is rendered. It's as though the RST-text isn't getting parsed but just used raw, as is.

**Environment**

- Python 3.9.1
- Sphinx 3.4.1
- Linux Mint 20

**Comment by Daltz333** [comment]
I'm not sure if this is just intentionally not supported. Images in tab headings is non-trivial.
