### ISSUE TITLE
Reference code instead of inline code?

### ISSUE THREAD

**Issue by JosephPJordan** [executablebooks/sphinx-tabs#111]
**Is your feature request related to a problem? Please describe.**

Just came across this, it's exactly what we are looking for.  

I'm far from a sphinx expert, so not sure if this is already possible, but it would be great to be able to reference code files from a different location instead of including the actual code inline in the page, with something like 
```.. literalinclude:: ../examples/example-code.json```

I tried a few different ways but couldn't get it to work.. maybe it just can't.  For example:

```
.. tabs::

    .. code-tab:: json classic

        .. literalinclude:: ../examples/example-code.json
```

**Describe the solution you'd like**

Would be great to reference code instead of putting it inline.  We are trying to use it for an code examples page where there would be maybe 10 examples or more on a page, and sometimes more, and each example can be 100 or more lines... so it just makes the page much longer.  Again, not sure it's even possible.

**Describe alternatives you've considered**

It does work with just putting the code inline, so definitely not a show-stopper.

**Additional context**

**Comment by foster999** [comment]
Hi @JosephPJordan, good question - that approach would make the document much more concise.

I think you should be able to achieve this with our `group-tab` and [the `literalinclude` directive](https://www.sphinx-doc.org/en/1.4.9/markup/code.html#directive-literalinclude):

```
.. tabs::

    .. group-tab:: json classic

        .. literalinclude:: ../examples/example-code.json
            :language: json
```

`code-tabs` currently expect the code directly, while `group-tab`'s can hold any content. So I'd use the `language` option for `literalinclude` to set the code language.

As long as you use consistent names for the tabs between tab sets, they should use the grouping action when changing between languages.

Hope this helps 😄

**Comment by JosephPJordan** [comment]
@foster999, thanks, that did the trick!!  Appreciate the quick response.
