### ISSUE TITLE
Make it possible to resize tabs

### ISSUE THREAD

**Issue by 0dminnimda** [executablebooks/sphinx-tabs#120]
Since I often need to specify code that exists in two versions, the large vertical size of the tabs gets in the way, so I would like to be able to resize them, at least in height.
I also want to be able to remove all margins and padding that delimits the text specified in the tabs.
Here's a good [example from opencv](https://docs.opencv.org/master/da/d6a/tutorial_trackbar.html)
I would be glad if something like this could be done.

[Alternative option](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/code_blocks.html#code-examples-in-multiple-languages) or [only this](https://pypi.org/project/sphinxcontrib-osexample/).

**Comment by Daltz333** [comment]
You can override the tab css. I don't see it in scope to make tabs dynamically resizable.

**Comment by 0dminnimda** [comment]
> I don't see it in scope to make tabs dynamically resizable.

Not dynamically (although this is an interesting feature), I'm only talking about static configuration.

> You can override the tab css

Ok then how can I do this?

**Comment by foster999** [comment]
You can add custom CSS files to any sphinx docs via the [sphinx conf.py file] (https://stackoverflow.com/a/37980230/8103477).

#117 will allow you to remove all of the current formating to start from scratch too

**Comment by 0dminnimda** [comment]
> You can add custom CSS files to any sphinx docs via the [sphinx conf.py file](https://stackoverflow.com/a/37980230/8103477).

Thanks for the help, now `sphinx-tabs` is [used in the documentation for cython](https://github.com/cython/cython/pull/4226#pullrequestreview-684079646), the python compiler!
