### ISSUE TITLE
Uncaught TypeError: exports is undefined

### ISSUE THREAD

**Issue by Martiix** [executablebooks/sphinx-tabs#128]
**Describe the bug**

I am using sphinx tabs in a sphinx project and it works nicely.

However in the network tab under "inspect element" in the browser I see the following error:
![image](https://user-images.githubusercontent.com/31621101/126118052-5d465750-e4d1-4403-b060-ab50b12274c3.png)
![image](https://user-images.githubusercontent.com/31621101/126117853-5deeabae-56ca-446b-8beb-8a7e64cab094.png)

**To Reproduce**

1. Go to https://support.zivid.com/latest/rst/reference-articles/zivid-3d-camera-technology/calculate-3d-capture-speed.html
2. Right click and press inspect
3. Open the network tab
4. Refresh page 
5. See error

Atm these can be displayed on the website on this url: 
https://support.zivid.com/latest/rst/reference-articles/zivid-3d-camera-technology/calculate-3d-capture-speed.html
or
https://support.zivid.com/latest/rst/academy/samples.html
remember to reload the page while the network tab is open to reproduce.

It also appears when building the documentation using localhost with the auto-build expansion

**Expected behavior**

No errors, like corresponding pages without tabs:
![image](https://user-images.githubusercontent.com/31621101/126116775-9b4cd370-aaa7-4a75-84d5-9e6ee5977007.png)

Actual behavior: 

![image](https://user-images.githubusercontent.com/31621101/126118655-d9341790-1218-4329-bdd4-e86f2f732993.png)

**Environment**

- Python Version [e.g. 3.7.1]: python==3.8.10
- Sphinx-tabs: sphinx-tabs==3.0.0
- Sphinx: sphinx==4.0.2
- Package versions or output of `jupyter-book --version`: Not in use
- Operating System: Built using Ubuntu 20.04

**Additional context**

Nothing

**Comment by foster999** [comment]
Thanks for raising this! 😊

The export statements aren't required for functionality (the tabs still work), and are only there to allow us to unit test the functions.

That said, it's not ideal that this is creating errors on every site. My JS knowledge isn't great, so would be grateful for any advice on this one. I believe that it's because I've used ESM syntax and the browser is treating it as common JS.

**Comment by TheTripleV** [comment]
Would including
```js
if (typeof exports === 'undefined') {
	exports = {};
}
```
above those lines be an acceptable workaround?

**Comment by foster999** [comment]
Thanks @TheTripleV, that looks ideal 😊

Would you like to add it through a PR? If not, I'm happy to add it when I get a moment.
