### ISSUE TITLE
Clicking an already selected tab hides the content

### ISSUE THREAD

**Issue by vberlier** [executablebooks/sphinx-tabs#141]
### Describe the problem

When you click a an already selected tab the content disappears. If you click it again the content will reappear. It shouldn't be possible to have zero tab selected.

### Link to your repository or website

https://sphinx-tabs.readthedocs.io/en/latest/#basic-tabs

### Steps to reproduce

1. Go to "Basic Tabs"
2. Click on the selected tab "Apples"
3. The tab gets deselected and the content disappears

**Comment by foster999** [comment]
Please [read the documentation](https://sphinx-tabs.readthedocs.io/en/latest/#sphinx-configuration) linked in your issue. This is the intended functionality, but can be disabled in your sphinx conf.py.
