### ISSUE TITLE
Extension load error

### ISSUE THREAD

**Issue by ronstone2000** [executablebooks/sphinx-tabs#149]
### Describe the bug

**context**
When I try to run sphinx via tox, this extension causes the job to error.

**expectation**
I expected the extension to load.

**bug**
requirements.txt:
```sphinx-tabs```
 
conf.py:
```extensions = ['sphinx_tabs.tabs']```
 
console:
```tox -e docs
Exception occurred:
  File ".tox/wra-docs/lib/python3.6/site-packages/sphinx_tabs/tabs.py", line 341, in setup
    app.add_javascript(path)
AttributeError: 'Sphinx' object has no attribute 'add_javascript'
```

### Reproduce the bug

With the tox requirement and conf.py extension set up show, run a tox job that calls sphinx-build against a conf.py that loads the sphinx-tabs extension.

### List your environment

Sphinx 4.2.0 
tox 3.13.3
Ubuntu: 20.04.2

**Comment by foster999** [comment]
Our code uses `add_js_file`, which is part of (the current sphinx API)[https://www.sphinx-doc.org/en/master/extdev/appapi.html]. I suspect you have an old version of sphinx-tabs installed?

**Comment by foster999** [comment]
Our code uses `add_js_file`, which is part of (the current sphinx API)[https://www.sphinx-doc.org/en/master/extdev/appapi.html]. I suspect you have an old version of sphinx-tabs installed?
