### ISSUE TITLE
issue with new dark mode of sphinx-tabs in themes that do not support dark mode

### ISSUE THREAD

**Issue by return42** [executablebooks/sphinx-tabs#152]
### Describe the bug

**context**

We use sphinx-tab and Pallets-Sphinx-Themes.  Pallets-Sphinx-Themes does not have a _dark_ theme.

Since 

- https://github.com/executablebooks/sphinx-tabs/pull/147 

has been merged, we got dark tabs in a _light_ theme, when the browser prefers a dark theme:

![image](https://user-images.githubusercontent.com/554536/157830928-13b1cf48-87ee-420e-bb94-2886ecb68975.png)

Rendered in a browser using _light_ theme:

![image](https://user-images.githubusercontent.com/554536/157831029-2364b6e8-d781-4c53-afec-841966a89f5e.png)

### Reproduce the bug

Use sphinx-tabs in a theme that does not have a _dark_ theme and setup your browser to use _dark_ theme.

EDIT: with https://github.com/executablebooks/sphinx-tabs/pull/147/commits/7915f63094d728654cfc9efd1d90fda479c285a5 reverted, the issue is fixed.

**Comment by return42** [comment]
If I'm not wrong, this condition is critical ..

https://github.com/executablebooks/sphinx-tabs/blob/53b6a635919a755aae2d9fc9f51337a4cd9b82f8/sphinx_tabs/static/tabs.css#L57-L60

it means: when the browser `prefers-color-scheme: dark` but the sphinx theme does not set a `<body data-theme="light">` the dark colors will be enabled.  In sphinx-themes that do not support dark/light the `data-theme` attribute is unset and the dark colors come in use.

**Comment by return42** [comment]
@Helveg if you have time, could you have a look at this issue / thanks!

**Comment by Helveg** [comment]
Oh, I thought `data-theme` was sphinx infused and available across all themes? Does anyone know if themes can be introspected for dark theme support?

**Comment by return42** [comment]
> Does anyone know if themes can be introspected for dark theme support?

AFAIK not from within CSS .. I think dark theme support is only available when `data-theme` is set?

Why not simply remove the entire `@media (prefers-color-scheme: dark)` block?

**Comment by Helveg** [comment]
> Why not simply remove the entire @media (prefers-color-scheme: dark) block?

That block is used to select the theme when the browser preference is used. The `data-theme` is an override that _may_ be set to override the color scheme preference, but if it isn't set, that means the browser preference should be used.

So 3 cases:

* `data-theme=dark`: always use dark mode
* `data-theme=light`: always use light mode
* `data-theme` not set, use browser preference

So any theme that is always dark, or always light, should set the `data-theme` attribute accordingly. I thought this was conventional, extrapolating from how the popular `furo` theme does it, but this is probably not commonly done then.

**Comment by Helveg** [comment]
> IMO it is just wrong to assume that "dark" is the default if data-theme is unset.

It doesn't do that, it uses the browser setting. You're right though, `furo` uses the `auto` value and that solves this issue :) I'll make it so that when `data-theme` is absent the light theme is used.

**Comment by return42** [comment]
> It doesn't do that, it uses the browser setting.

Sorry wrong wording, more precise: "it is just wrong to assume that "dark" is supported by the theme if data-theme is unset"

> I'll make it so that when `data-theme` is absent the light theme is used (and incorporate your PR comments).

Thanks a lot!

BTW: as long https://github.com/executablebooks/sphinx-tabs/pull/153 is merged I am also unable to overwrite the `tab.css` :-)

**Comment by Helveg** [comment]
I'm not a maintainer of this project :(

**Comment by return42** [comment]
> I'm not a maintainer of this project :(

No problem, send your PR and then we can ask the maintainers to merge both PRs and build a new release.

**Comment by return42** [comment]
@Helveg you don't need to fix it anymore, I send #154 to fix this issue.

@foster could you review & merge #153 and #154 .. and build / deploy a new release? .. thanks a lot!
