### ISSUE TITLE
RFE: Replace use of `pkg_resources` with `importlib.metadata`

### ISSUE THREAD

**Issue by kloczek** [executablebooks/sphinx-tabs#159]
### Context

See discussions:
[astropy/astropy#11091](https://github.com/astropy/astropy/pull/11091)
[pypa/pip#7413](https://github.com/pypa/pip/issues/7413)

```console
[tkloczko@devel-g2v SRPMS]$ rpm -ql python-sphinx-tabs | grep py$ | xargs grep pkg_resources
/usr/lib/python3.8/site-packages/sphinx_tabs/__init__.py:__import__("pkg_resources").declare_namespace(__name__)
```

**Comment by foster999** [comment]
Thanks, that's great to know a better alternative exists. Is support for python < 3.8 built in or do we need to add anything to support the backport?

**Comment by kloczek** [comment]
I'm not sure.
At the moment my main devel systems are (still) using python 3.8 (3.8.13).
Soon I'll move all my stuff to 3.9 and than to 3.10.
Nevertheless lokks like `pkg_resources` caused some issues with building sphinx documentation so after opening `setuptools` ticket I've learned that this issue will be not solved because genelereally `setuptools` maintainer wamnt to remove that module from `setuptools` tree.
