### ISSUE TITLE
Move away from deprecated/unmaintained sphinx_testing

### ISSUE THREAD

**Issue by thesamesam** [executablebooks/sphinx-tabs#176]
### Describe the bug

**context**
When trying to mark support for Python 3.11 to sphinx-tabs in our Gentoo packaging, we had to stop because one of its test dependencies, sphinx_testing, fails tests with Python 3.11 and is now archived upstream & unmaintained.
 
**expectation**
I expected all test dependencies to support Python 3.11.

**bug**

sphinx-tabs relies on an unmaintained package (sphinx_testing) for tests which prevents Python 3.11 compatibility.

**problem**
This is a problem for people migrating their systems and distributions to Python 3.11 because they can't test sphinx-tabs correctly first, which is often a blocker for making the migration at all (if it can't be tested, people don't feel comfortable using it with Python 3.11, so the package is usually removed instead).

### Reproduce the bug

1. Install Python 3.11.
2. Try to run the sphinx-tabs test suite.

### List your environment

- Python 3.11
- Gentoo

**Comment by thesamesam** [comment]
This came up at https://github.com/executablebooks/sphinx-tabs/issues/126#issuecomment-1001989574 before too.

**Comment by foster999** [comment]
Removed this dependency in the latest release
