### ISSUE TITLE
Conflict with pydata-sphinx-theme

### ISSUE THREAD

**Issue by K20shores** [executablebooks/sphinx-tabs#180]
### Describe the bug

**context**
When I do use this package with pydata-sphinx-theme, the version switcher for that project does not work.

**expectation**
I expected both packages to work without affecting each other.

**bug**
But instead adding `sphinx_tabs.tabs` to the extensions, without even using a tab, the version switcher for that package no longer works. I filed an [issue](https://github.com/pydata/pydata-sphinx-theme/issues/1496) on that repository, but I figured it might be useful to have this tracked here as well.

**problem**
This is a problem for people wanting use this package with pydata-sphinx-theme

### Reproduce the bug

Just follow the steps listed in [this issue](https://github.com/pydata/pydata-sphinx-theme/issues/1496)

**Comment by foster999** [comment]
Thanks for this, what do you mean by version switcher?

**Comment by K20shores** [comment]
> Thanks for this, what do you mean by version switcher?

Here's an example from the theme home page. There's a dropdown you can choose to see document version.

<img width="865" alt="Screenshot 2023-10-05 at 11 53 25 AM" src="https://github.com/executablebooks/sphinx-tabs/assets/13836216/f1e3dc60-78dd-4b23-8265-420a81989483">

For whatever reason, sphinx tabs prevents something from loading. I'm not positive, but I believe there is a script added to the page which makes a get request for the switcher URL. I don't quite understand how this extension would prevent that, but of the extensions we use in my project, disabling the tabs is the only one that allowed our switcher to show.

**Comment by mathpl** [comment]
I got the same issue and with a little bit of debugging I think I understand the area of the code that's problematic, I'm not quite sure how to properly solve it as I don't have much experience developing for sphinx. I'll put a PR up with what fixes it for me so you can have a look.

**Comment by mathpl** [comment]
Proposed fix: https://github.com/executablebooks/sphinx-tabs/pull/181

**Comment by foster999** [comment]
Fixed in the latest release, thanks @mathpl 🥳
