### ISSUE TITLE
sphinx-tabs inadvertently removes css and js

### ISSUE THREAD

**Issue by peytondmurray** [executablebooks/sphinx-tabs#183]
### Describe the bug

**context**
When I use the `sphinx-tabs` extension and I include css or js in specific pages, [this function](https://github.com/executablebooks/sphinx-tabs/blob/eac2a227ca0d375bad3706cf1cf170d760510a22/sphinx_tabs/tabs.py#L314) removes it even if I intend for it to be included.

**expectation**
I expect `sphinx-tabs` to leave my included css/js alone. Rather than including `sphinx-tabs` assets globally and then removing them upon `html-page-context` if the page _doesn't_ have any tabs directives, this package should only insert those assets if the page _does_ have a tabs directive, not the other way around. This can also be done at `html-page-context` time.

**bug**
Instead, `sphinx-tabs` automatically removes all css/js unless it is included on every single page.

**problem**
This is a problem for people who want to include assets on specific pages to keep page load times down, but who also want to use tabs. Both sphinx docs and `pydata-sphinx-theme` docs suggest inserting css/js assets upon `html-page-context`, so the current behavior is extremely confusing because your assets get removed in the background, leaving you wondering how this is happening.

### Reproduce the bug

Here's a small working example: https://github.com/peytondmurray/minimalsphinx/tree/per-page-css

You'll see if you run `make html` that the `apidocs.html` will only include the css if `sphinx-tabs` is disabled.

**Comment by foster999** [comment]
This is potentially the same as #180, or caused by the fix of that issue. What version of the package are you using?

**Comment by foster999** [comment]
Thanks for including the example - this pins an earlier version, so please try it with the latest

**Comment by peytondmurray** [comment]
@foster999 Thanks, you're absolutely right that upgrading fixed the issue. I looked at the differences between `3.4.1` and `3.4.4` and I'm stumped as to why this now works. Here's the difference:

![image](https://github.com/executablebooks/sphinx-tabs/assets/14017872/2a1d8628-f2a4-4c8e-a7a9-fcd90f549f61)

What exactly does moving the slicing operation do here? `v3.4.1` has

```python
context["css_files"] = context["css_files"][:]
```

which in my mind means 'set the `context["css_files"]` list equal to the slice containing the entire list of `context["css_files"]`'. In `v3.4.4` the relevant lines read 'set the slice containing the entire list of context`["css_files"]` equal to the list of `context["css_files"]`.' Naively I would expect the operation in either case to do nothing, basically, but I must be wrong :shrug:. I guess I'm [not the only one struggling to understand this](https://github.com/executablebooks/sphinx-tabs/pull/181), did you ever figure it out?

**Comment by foster999** [comment]
Afraid I'm still baffled by the slicing too! My feeling was that it's something to do with updating all references to the object (and nested objects inside it) vs just updating the single reference. Kinda like shallow vs deep copying. But didn't understand how that lead to the issue.

I was surprised the issue hadn't come up sooner, though it seems to be themes rather than other extensions that were affected. So maybe something to do with the order that sphinx evaluates things 🤷

**Comment by peytondmurray** [comment]
Thanks again for the help!
