### ISSUE TITLE
RemovedInSphinx90Warning ("The str interface for _JavaScript objects is deprecated")

### ISSUE THREAD

**Issue by ru-fu** [executablebooks/sphinx-tabs#197]
### Describe the bug

When building with Sphinx 8.x, sphinx-tabs gives the following errors:

```
.../.sphinx/venv/lib/python3.10/site-packages/sphinx_tabs/tabs.py:335: RemovedInSphinx90Warning: The str interface for _JavaScript objects is deprecated. Use js.filename instead.
  if path.suffix == ".js" and path.as_posix() in context["script_files"]:
.../.sphinx/venv/lib/python3.10/site-packages/sphinx_tabs/tabs.py:336: RemovedInSphinx90Warning: The str interface for _JavaScript objects is deprecated. Use js.filename instead.
  context["script_files"].remove(path.as_posix())
```

These aren't actually Sphinx errors and don't cause the build to fail, but I haven't figured out how to filter them out, so they make the build log unreadable.
And it will probably render sphinx-tabs unusable in Sphinx 9.x.

Seems the deprecation message has been introduced in this commit: https://github.com/sphinx-doc/sphinx/commit/49dc0dd3999f66f27728b974394585422f10d947

### Reproduce the bug

Build a doc set that includes tabs with Sphinx 8.x.

**Comment by dimaqq** [comment]
I think changing the title to include "str interface for _JavaScript" would make this issue a bit more visible and precise.

**Comment by kartben** [comment]
My understanding is that there should have been no dependency on internal/undocumented API in the first place. PR #198 is taking a stab at fixing this issue -- would be great to get some help reviewing it and potentially getting a release with the fix out. Thanks!
