### ISSUE TITLE
How to make custom lexers working in code-tab?

### ISSUE THREAD

**Issue by honzajavorek** [executablebooks/sphinx-tabs#34]
When I add a custom lexer to Sphinx, it doesn't seem to be supported by `sphinx-tabs`:

```python
def setup(app):
    app.add_lexer('openapi2', OpenAPI2Lexer())
```

```
Exception occurred:
  File "/Users/honza/Projects/dredd/venv/lib/python3.7/site-packages/sphinx_tabs/tabs.py", line 212, in run
    tab_name = ' '.join(args[1:]) if len(args) > 1 else LEXER_MAP[lang]
KeyError: 'openapi2'
The full traceback has been saved in /var/folders/r4/pw8r6nrn549dd1fh9n82k2x40000gp/T/sphinx-err-bzkj5vvc.log, if you want to report the issue to the developers.
```

This is the case also for lexers added by extensions.

**Comment by honzajavorek** [comment]
Hmm, I was wrong, it seems to work for lexers from installed extensions. Made me think whether it's because the sphinx-tab code executes before the `setup()` in my `conf.py` happens? 🤔

**Comment by kahlil29** [comment]
@honzajavorek  You are referring to syntax highlighting based on your custom syntax rules right? Did you manage to get this to work?

**Comment by honzajavorek** [comment]
My configuration is [here](https://github.com/apiaryio/dredd/blob/master/docs/conf.py). I solved it by using `group-tab` with explicit code markup instead of `code-tab`. I often need to have also text in the tab apart from the code block anyway, so it's more robust solution to my problem.

**Comment by kahlil29** [comment]
@honzajavorek Thanks for your informative reply! 👍 😄

**Comment by foster999** [comment]
This should be fixed by #79, as `code-tab` would pass all arguments/options to Sphinx's `code-block` directive.

**Comment by honzajavorek** [comment]
I won't be able to verify as I'm not in a situation where I need this particular feature anymore. (But I'm still a big fan of sphinx-tabs otherwise, using it on other projects, keep up the good work!)

**Comment by foster999** [comment]
No worries, it was actually only looking for lexers from `pygments`. Have implemented this now and added a test 👍 

Usage as:

```
.. tabs::

   ..code-tab:: lexeralias

      Code

   ..code-tab:: lexeralias2 Tab label

      More code
```

**Comment by foster999** [comment]
@chrisjsewell feel free to close this with #79 and v1.3.0 released 😄
