### ISSUE TITLE
Warning: app.info() is now deprecated. Use sphinx.util.logging instead.

### ISSUE THREAD

**Issue by niklibrato** [executablebooks/sphinx-tabs#49]
It's probably not a big deal but I get this warning now running Sphinx v1.8.5. Should I be concerned?

```
/deploy/sphinxext/sphinx_tabs/tabs.py:250: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  app.info('Copying tabs assets... ', nonl=True)
Copying tabs assets... /deploy/sphinxext/sphinx_tabs/tabs.py:263: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  app.info('done')
done
```

**Comment by djungelorm** [comment]
It shouldn't cause any issues. I'll update it to use the new API in the next version which will make this warning go away.

**Comment by djungelorm** [comment]
Which version of sphinx tabs are you using? Looks like this is already fixed in version 1.1.12

**Comment by lasofivec** [comment]
If @niklibrato had the same issue as me, he installed sphinx-tabs with `conda`:

https://anaconda.org/tiledb/sphinx-tabs

which downloads an old version of `sphinx-tabs` (v1.1.7)

**Comment by chrisjsewell** [comment]
Closing this as it has indeed been fixed, but I'll also release sphinx-tabs on conda-forge at some point (see #78)
