### ISSUE TITLE
Improve Latex/pdf support

### ISSUE THREAD

**Issue by stefanodavid** [executablebooks/sphinx-tabs#57]
Support for tabs in latex/pdf was required in #19, apparently added in PR #23 (commit 3f9bf17), but it is not part of the current release. Was it ever part of a release and are there any plan to (re)introduce that feature? If I apply the code in that commit to the current release, the output latex code does not change at all from the current release... 

I use currently as a workaround the `.. only::` directives with tabs for html and topics for latex, but it would be better to have it automatic with sphinx_tabs.

**Comment by ScriptAutomate** [comment]
I have had to do something very similar in order to allow compatibility between my PDF and HTML builds. I've had to go so far as make a build script that gets run in my CI pipelines that uses `sed` replacements to ensure the PDF comes out okay, using admonitions in the rst before the PDFs are built.

```bash
# sphinx-tabs formatting workaround
## Replacing tabs with admonitions, to properly render
for TAB_FILE in $(grep -R '.. tabs::' docs/ | cut -d':' -f1 | sort | uniq)
do
    sed -i 's/\ \ \ \.\.\ tabs:://g' $TAB_FILE
    sed -i 's/\ \ \ \ \.\.\ tab::/\ \ \.\. admonition::/g' $TAB_FILE
done
```

It's literally modifying the rst temporarily when the pipeline job for building PDFs runs. It's been the best way for me to make the lives of other contributors (and myself) easier. Once it can work fine out-of-box, I'll won't have to remember it for other projects using this plugin that also generate PDFs

**Comment by chrisjsewell** [comment]
yep its on the TODO list, when I start restructuring some of the parsing logic, to work better with [MyST-Parser](https://myst-parser.readthedocs.io/)

**Comment by Daltz333** [comment]
Since we pushed the new version, is this issue still present? On our PDF, it prints each tab as it's own thing.

**Comment by stefanodavid** [comment]
Hi @Daltz333 thanks for you efforts!

Since opening this issue, I moved projects that required a PDF to sphinx-panels and used `tabbed::`, but I made a quick test with `tabs::` and `tabbed::`. By comparing the results, `tabs::` just writes the tab's title as a separate paragraph, while `tabbed::` puts  it as a `\subsubsection*`, and I prefer the latter which makes clear that each tab is a separate thing. 
But my initial request is now satisfied, so you can close the issue.

**Comment by jdillard** [comment]
> On our PDF, it prints each tab as it's own thing.

What is "our PDF" here? I don't see any PDF downloads in the docs: https://sphinx-tabs.readthedocs.io

**Comment by Daltz333** [comment]
My person project frc-docs.readthedocs.io

**Comment by jdillard** [comment]
Got it, thanks! Here is an example from your docs PDF for the curious:

![image](https://user-images.githubusercontent.com/3474095/119239852-c6860c80-bb00-11eb-8f08-0fb048e07143.png)

I wonder if turning on the PDF for the `sphinx-tabs` docs would be worthwhile.

**Comment by krzychb** [comment]
Hi,

Is it possible to change the order of how tabs and the corresponding content appear in PDF?

Tab 1
Content of tab 1
Tab 2
Content of Tab 2

Now we see first all the tabs and then all the content so the reader will likely be confused about what content is for what tab.
