### ISSUE TITLE
Support Sphinx 3

### ISSUE THREAD

**Issue by Daltz333** [executablebooks/sphinx-tabs#58]
```
Running Sphinx v3.0.0b1
c:\users\dalton smith\appdata\local\programs\python\python37-32\lib\site-packages\sphinx_tabs\tabs.py:341: RemovedInSphinx40Warning: The app.add_javascript() is deprecated. Please use app.add_js_file() instead.
  app.add_javascript(path)
```

**Comment by ScriptAutomate** [comment]
Some added notes:

`add_javascript()` is a deprecated Sphinx method, and should be updated to remove any RemovedInSphinx warning messages in Sphinx 3.x.x when building.

- Sphinx 3.x.x will show RemovedInSphinx warning messages about deprecation, but both the old format and expected format will work either way for the moment.
- Sphinx 4.x.x will be dropping all support for `.add_javascript()`, moving to `.add_js_file()`. The old format will no longer work in Sphinx 4.x.x, so it needs to be fixed.
- This change happened back in 1.8, so should work with sphinx>=1.8.0 after being fixed.
  - [Sphinx Docs: add_js_file](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file)
