### ISSUE TITLE
Incorrect Release Link in README

### ISSUE THREAD

**Issue by ColonelPanicks** [executablebooks/sphinx-tabs#61]
Just a little one, the RTD `requirements.txt` line hasn't properly been bumped to latest release version, it reads:
```
https://github.com/djungelorm/sphinx-tabs/releases/download/v1.1.12/sphinx-tabs-1.1.13.tar.gz
```

Whereas it should be
```
https://github.com/djungelorm/sphinx-tabs/releases/download/v1.1.13/sphinx-tabs-1.1.13.tar.gz
```

The `v1.1.12` after `download` should be `v1.1.13`

**Comment by jdillard** [comment]
This looks to have been addressed in PR #64.
