### ISSUE TITLE
Overriding wide tables in theme stops Sphinx-tabs working

### ISSUE THREAD

**Issue by DeanMFenton** [executablebooks/sphinx-tabs#63]
I am updating a customer's RTD site and could not get tabs to appear. Eventually I commented out the following in conf.py and the tabs now work but we have the problem of wide tables scrolling off to the right. (This was what the statement in conf.py stops) Is it possible to fix sphinx-tabs so that I can reintroduce the lines to conf.py?

html_context = {
     'css_files': [
           '_static/theme_overrides.css',  # override wide tables in RTD theme
           ],
     }

Thanks, Dean Fenton

**Comment by DeanMFenton** [comment]
For more info on what the code above does, see 
https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html

**Comment by FredHall** [comment]
This is a bug in Rackspaces instructions, not in Sphinx-tabs. 

Follow these instruction https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html to add custom CSS to over ride the theme
