### ISSUE TITLE
Add tabindex attribute to improve accessibility 

### ISSUE THREAD

**Issue by jdillard** [executablebooks/sphinx-tabs#66]
If the [tabindex attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) of `tabindex="0"` was added to each `a.item` anchor, the javascript could be modified slightly to allow keyboard control of the tabs.

I'll look at opening a PR for this, but wanted to create the issue first.

**Comment by itmightbecody** [comment]
Some related material for ARIA labels, which honestly may be a separate issue in terms of implementation, but related in terms of accessibility: https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-2/tabs.html

**Comment by jdillard** [comment]
Perfect example, with example code! That is probably the correct implementation, I will have to look over both resources.
