### ISSUE TITLE
Maitenance status of project

### ISSUE THREAD

**Issue by Daltz333** [executablebooks/sphinx-tabs#67]
Is this project still maintained?

**Comment by pradyunsg** [comment]
Hi @djungelorm! Is this project actively maintained? If not, would you be willing to add someone as a co-maintainer on the project?

I'm happy to share the maintenance workload if you're OK with that. :)

**Comment by chrisjsewell** [comment]
We would also be interested in moving this to https://github.com/executablebooks (linking https://github.com/executablebooks/sphinx-panels/issues/28)

**Comment by djungelorm** [comment]
Yes, unfortunately I don't have time to maintain the project, and have no idea when I might, so getting some other people on board would be good to keep it alive!

Thanks for the offer @chrisjsewell I'd be happy to have your team maintain the project :)

**Comment by chrisjsewell** [comment]
> Thanks for the offer @chrisjsewell I'd be happy to have your team maintain the project :)

Thanks @djungelorm 😄
@choldgraf, I assume this is ok with you, if so I believe you have some experience with this kind of transfer?

**Comment by choldgraf** [comment]
@djungelorm I just added you as a maintainer to the `executablebooks/` org. Once you accept, go to `settings` and at the bottom should be a button to transfer the repository ✨

**Comment by djungelorm** [comment]
Done! :) Let me know if there's anything else you need.

**Comment by chrisjsewell** [comment]
Brilliant thanks @djungelorm 
If you could add https://pypi.org/user/ebp-bot as a maintainer to the PyPi package, then at some point I'll move the testing to GitHub Actions and I'll ask you to turn off the TravisCI

**Comment by choldgraf** [comment]
And maybe more generally @djungelorm can you think of any other permissions that would need to be transferred that we haven't thought about?
