### ISSUE TITLE
Sphinx-tabs are not working  with sphinx 3.0.4

### ISSUE THREAD

**Issue by Dhiraj240** [executablebooks/sphinx-tabs#70]
Hello,
I am working on OpenDaylight project as an intern and we planned to add ```code-tabs``` for our documentation but I get error like Unkown "tabs" even after adding the requirements in the required areas of documentation.

Is it not compatible with sphinx 3.0.4 version?

**Comment by Daltz333** [comment]
It is. And it's ``code-tab`` not ``code-tabs``
