### ISSUE TITLE
Support for group-tab and code-tab in Markdown

### ISSUE THREAD

**Issue by foster999** [executablebooks/sphinx-tabs#71]
As documented in this [issue](https://github.com/executablebooks/jupyter-book/issues/787#issue-657518874), `group-tab` and `code-tab` generate `reStructuredText` when used with a `Markdown` parser. This is because rST is hard coded into their directives. Would it be possible to alter these to generate the appropriate Markup, as the basic `tab` functions?

**Comment by chrisjsewell** [comment]
Now that this project is part of EBP, this will definitely be getting fixed 😄

**Comment by foster999** [comment]
That's really great, glad it'll be getting some TLC! 😃

I'd already worked on this for my own use, so have raised a PR with those changes. It wasn't meeting the old python 2 test, but I'd be grateful for any comments to get it up to scratch!
