### ISSUE TITLE
Remember last `group-tab` selection between pages

### ISSUE THREAD

**Issue by foster999** [executablebooks/sphinx-tabs#80]
**Is your feature request related to a problem? Please describe.**

I'd like the `group-tab` selection to persist between different pages. For example, consider a book containing code snippets in multiple languages. Users might like to select a particular language to reference throughout the book, rather than selecting that language's tab on each page.

**Describe the solution you'd like**

I'd considered storing the last `group-tab` selection in the session, so that it persists between pages (i.e. across a `jupyter-book`). Would be great to know if there's a more appropriate way to do this.

**Comment by shireenrao** [comment]
This would be a great enhancement!

**Comment by foster999** [comment]
Will give this a try after JS is cleaned up in #87
