### ISSUE TITLE
RFE: Reduce project's JS/CSS payload size

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-tabs#87]
**Is your feature request related to a problem? Please describe.**

Currently, this extension results in 50+ kB of assets across 7+ network requests to be added to each page for a project's documentation.

**Describe the solution you'd like**

Significantly lowered payload size (drop the dependency on semantic-ui?) and consolidate CSS/JS files to reduce the number of network requests needed.

**Describe alternatives you've considered**

**Additional context**

This would also make it easier for "downstream" themes to customize how the tabs look, if the CSS for this project is self-contained in a single file. :)

**Comment by chrisjsewell** [comment]
Also, I've recently realised that its not too hard to add js only for specific pages, i.e. those containing tab nodes (see https://github.com/executablebooks/sphinx-book-theme/issues/165#issuecomment-682212704).
So I think this would be a complimentary improvement

**Comment by pradyunsg** [comment]
Would you be open to a complete rewrite of this package, similar to what I did for sphinx-autobuild? 👀

**Comment by chrisjsewell** [comment]
Not really lol, I've already set it up consistent with the EBP guidelines in #76

Obviously I'm open to suggestions and improvements where beneficial.
But I will never agree to using a `src` folder 🤣

**Comment by Daltz333** [comment]
``src`` for python is just weird....

**Comment by chrisjsewell** [comment]
> `src` for python is just weird....

FYI, I mainly said this to "pull @pradyunsg's leg", since I know he is a bit of a fan https://github.com/pypa/packaging.python.org/issues/320 lol

**Comment by pradyunsg** [comment]
> Obviously I'm open to suggestions and improvements where beneficial.

Noxify!

**Comment by chrisjsewell** [comment]
> Noxify!

Well there already a tox.ini.
I'd rather just use that for 2 reasons

1. tox is just more mature and well-used/known
2. I personally use also the tox-conda plugin which is super useful, and I don't see a nox equivalent (apart from hard-coding conda into nox.py itself)

nox has its uses; the live-rebuilds for messing around with scss in sphinx-book-theme is helpful.
But I'm not sure, for a project less based around theming, that the pros outweigh the cons?

**Comment by pradyunsg** [comment]
Fair enough. :) As long as my finger-memory of `.ox -s (tests?|lint|docs) works, I'm a happy kiddo. :)

**Comment by chrisjsewell** [comment]
`nox -s lint` was actually a nitpick I noted in sphinx-book-theme/autobuild.
Surely its redundant to create a virtualenv, in which to run pre-commit, which then creates its own virtualenv 😜

**Comment by pradyunsg** [comment]
It is super redundant. OTOH, the main reason I do this is consistency across projects (not all my projects use pre-commit, yet!) and newbie-friendliness. It's easier to tell newcomers to "install nox, and use these nox commands" than "install nox and pre-commit, and set up pre-commit for linting, everything else uses these nox commands".

And for anyone familiar enough with pre-commit, well, `pre-commit run --all-files` still works. :)

**Comment by chrisjsewell** [comment]
linking https://github.com/executablebooks/meta/issues/119

**Comment by pradyunsg** [comment]
@chrisjsewell Thoughts on a complete rewrite of this project, to drop the dependency on semantic-ui? It should make it easier to tweak the JS to implement stuff like #84 and #47.

**Comment by chrisjsewell** [comment]
I'd say possibly, but it's low on the priority list.
Obviously we now have, https://sphinx-panels.readthedocs.io/en/latest/#tabbed-content for a CSS only approach,
and first I'd like to get https://github.com/executablebooks/meta/issues/137 sussed

**Comment by pradyunsg** [comment]
This RFE is still valid, and @foster999 has made #94, which looks like it does the needful. I'm not gonna come around to this myself anytime soon though. Context [here](https://github.com/executablebooks/meta/issues/145#issuecomment-708667465).
