### ISSUE TITLE
Option to collapse tabs by default

### ISSUE THREAD

**Issue by foster999** [executablebooks/sphinx-tabs#89]
**Describe the solution you'd like**

Following #73, it might be useful to have an option which collapses a set of tabs by default.

Alternatively, it could provide a conifg option to close all tabs by default. 

Any call for this?

Probably like:
```
.. tabs::
   :collapsed:
  
   .. tab :: Stuff

      Content
```

Implementation could disable addition of `active` class to first tab.

**Comment by robinmacharg** [comment]
I'd also like to be able to prevent tabs collapsing on the second click.  Not sure if that feature already exists?

**Comment by foster999** [comment]
Good suggestion @robinmacharg - this could certainly be added as a sphinx configuration option

**Comment by foster999** [comment]
@robinmacharg - I've included this in the latest version via the sphinx config option `sphinx_tabs_disable_tab_closing` 👍🏻

**Comment by alexander-schranz** [comment]
I tried out `sphinx_tabs_disable_tab_closing` but it seems to have no effect. I tried using with the `alabaster` and `furo` theme both close the tab when I click on it. I have configured in my `conf.py` following the other option for disable css loading works:

```py
sphinx_tabs_disable_tab_closing = True # does not work
sphinx_tabs_disable_css_loading = True
```

@foster999 was does option renamed?

**Comment by foster999** [comment]
@alexander-schranz, sorry for the slow reply. Do you have an example of this not working?

I've just tried with our docs build and it seems to work. Might be worth deleting the previous build folder and building again, as sphinx might no rebuild if the page content hasn't changed

**Comment by alexander-schranz** [comment]
@foster999 Thx still for your response. I retried it on the project where I did stumble over it but I can not longer reproduce the issue. I since the sphinx and the theme was update, but it could also be a cache issue because not 100% what is being cached in the CI. So for me the option is working now.

**Comment by foster999** [comment]
Thanks for confirming, glad to hear it's working now

**Comment by foster999** [comment]
Closing this, as no further interest in the original suggestion
