### ISSUE TITLE
2.0.0 version breaks pdf generation

### ISSUE THREAD

**Issue by nicozanf** [executablebooks/sphinx-tabs#99]
I cannot anymore obtain any pdf output.

Even with the simple "Apple & Pear" example, that still works fine with 1.3.0, I always get the following error from rinohtype:

rinoh.frontend.sphinx (0.4.2) from /home/nico/.local/lib/python3.8/site-packages/rinoh/frontend/sphinx/__init__.py
Traceback (most recent call last):
  File "/home/nico/.local/lib/python3.8/site-packages/rinoh/frontend/__init__.py", line 27, in map_node
    return cls._mapping[node_name.replace('-', '_')](node, **context)
KeyError: 'div'

The simple workaround that I've found is to downgrade to sphinx-tabs 1.3.0.

Ubuntu 20.10
Sphinx version: 3.2.1
Python version: 3.8.6 (CPython)
Docutils version: 0.16 release
Jinja2 version: 2.11.2

**Comment by foster999** [comment]
Thanks @nicozanf. I'm not familiar with rinohtype, please could you let me know what command you're using to build the basic example?

This would be a good opportunity to get some tests implemented for pdf builds too.

**Comment by nicozanf** [comment]
Thank you!

I was trying to reproduce the problem with the simplest possible example, but I've found that this works fine on both versions ;-(

Sorry, I need more time to check exactly what's wrong. And I'll surely post the simplest possible example, in order to let you implement them for pdf builds test.

Nico

**Comment by Daltz333** [comment]
I cannot reproduce this. PDF builds fine for me

**Comment by nicozanf** [comment]
I've been able to reproduce the bug, even with the simple test_pdf example that I'm attaching here [test_pdf.zip](https://github.com/executablebooks/sphinx-tabs/files/5900401/test_pdf.zip). You will need to 'pip install rinohtype' before using it. See the enclosed readme.txt for simple instructions.

**NB**: after a succesfull run you must delete the hidden folder 

`temp/.doctrees`

(where temp is the building folder in my example) otherwise it will be reused and you will never get an error anymore!
